<?php
// ASX 300 Constituents - Updated April 2026
// Save as asx300_tickers.php in the same folder as redline.php

$stocks = [
    '4DX.AU', '5EA.AU', '88E.AU', 'A2M.AU', 'AAI.AU', 'ABB.AU', 'ABC.AU', 'ABP.AU', 
    'AFI.AU', 'AGL.AU', 'AIA.AU', 'AIZ.AU', 'ALD.AU', 'ALK.AU', 'ALL.AU', 'ALQ.AU', 
    'ALX.AU', 'AMC.AU', 'AMP.AU', 'ANN.AU', 'ANZ.AU', 'AOV.AU', 'APA.AU', 'APE.AU', 
    'APX.AU', 'APZ.AU', 'ARB.AU', 'ARF.AU', 'ARG.AU', 'ARU.AU', 'ASB.AU', 'ASK.AU', 
    'ASX.AU', 'AUB.AU', 'AUI.AU', 'AZJ.AU', 'BC8.AU', 'BCI.AU', 'BEN.AU', 'BFL.AU', 
    'BGA.AU', 'BGP.AU', 'BHP.AU', 'BKI.AU', 'BGL.AU', 'BOQ.AU', 'BPT.AU', 'BRE.AU', 
    'BRG.AU', 'BSL.AU', 'BVS.AU', 'BWP.AU', 'BXB.AU', 'CAR.AU', 'CAT.AU', 'CBA.AU', 
    'CBO.AU', 'CDA.AU', 'CEN.AU', 'CGF.AU', 'CHC.AU', 'CHI.AU', 'CIA.AU', 'CIN.AU', 
    'CIP.AU', 'CKF.AU', 'CLW.AU', 'CMM.AU', 'CMW.AU', 'CNI.AU', 'CNU.AU', 'COH.AU', 
    'COL.AU', 'CQE.AU', 'CQR.AU', 'CPU.AU', 'CSC.AU', 'CSL.AU', 'CTD.AU', 'CU6.AU', 
    'CWY.AU', 'CYL.AU', 'DBI.AU', 'DDR.AU', 'DGT.AU', 'DMP.AU', 'DNL.AU', 'DOW.AU', 
    'DPM.AU', 'DRR.AU', 'DTR.AU', 'DUI.AU', 'DVP.AU', 'DXS.AU', 'DYL.AU', 'EBO.AU', 
    'EDV.AU', 'ELD.AU', 'ELS.AU', 'ELV.AU', 'EMR.AU', 'EOS.AU', 'EQR.AU', 'ERA.AU', 
    'EVN.AU', 'EVT.AU', 'FFM.AU', 'FBU.AU', 'FLT.AU', 'FMG.AU', 'FPH.AU', 'FRW.AU', 
    'GCI.AU', 'GDG.AU', 'GGP.AU', 'GLF.AU', 'GLS.AU', 'GMD.AU', 'GMG.AU', 'GNC.AU', 
    'GNE.AU', 'GNP.AU', 'GOZ.AU', 'GPT.AU', 'GQG.AU', 'GYG.AU', 'HDN.AU', 'HGH.AU', 
    'HLI.AU', 'HMC.AU', 'HSN.AU', 'HUB.AU', 'HVN.AU', 'IAG.AU', 'IEL.AU', 'IFL.AU', 
    'IFT.AU', 'IGO.AU', 'ILU.AU', 'IMD.AU', 'INA.AU', 'IPH.AU', 'IPX.AU', 'IRE.AU', 
    'JBH.AU', 'JDO.AU', 'JHX.AU', 'KAR.AU', 'KCN.AU', 'KLS.AU', 'L1G.AU', 'LFG.AU', 
    'LFS.AU', 'LIN.AU', 'LLC.AU', 'LNW.AU', 'LOV.AU', 'LSF.AU', 'LTR.AU', 'LYC.AU', 
    'MAH.AU', 'MAQ.AU', 'MAD.AU', 'MAF.AU', 'MCY.AU', 'MEZ.AU', 'MFF.AU', 'MFG.AU', 
    'MGR.AU', 'MGH.AU', 'MI6.AU', 'MIN.AU', 'MLX.AU', 'MMS.AU', 'MND.AU', 'MP1.AU', 
    'MPL.AU', 'MQG.AU', 'MSB.AU', 'MTS.AU', 'MXT.AU', 'NAB.AU', 'NAN.AU', 'NCK.AU', 
    'NEC.AU', 'NEM.AU', 'NEU.AU', 'NGI.AU', 'NHC.AU', 'NHF.AU', 'NIC.AU', 'NSR.AU', 
    'NST.AU', 'NUF.AU', 'NWH.AU', 'NWL.AU', 'NWS.AU', 'NXG.AU', 'NXT.AU', 'OBM.AU', 
    'OCL.AU', 'ORA.AU', 'ORG.AU', 'ORI.AU', 'PDN.AU', 'PDI.AU', 'PGF.AU', 'PLS.AU', 
    'PL8.AU', 'PME.AU', 'PMV.AU', 'PNI.AU', 'PNR.AU', 'PPC.AU', 'PPT.AU', 'PRN.AU', 
    'PRU.AU', 'PWH.AU', 'PXA.AU', 'PYC.AU', 'QAN.AU', 'QBE.AU', 'QRI.AU', 'QUB.AU', 
    'REA.AU', 'RDX.AU', 'REG.AU', 'REH.AU', 'RGN.AU', 'RHC.AU', 'RIC.AU', 'RIO.AU', 
    'RMD.AU', 'RPL.AU', 'RRL.AU', 'RSG.AU', 'RWC.AU', 'RYM.AU', 'S32.AU', 'SCG.AU', 
    'SDF.AU', 'SEK.AU', 'SGH.AU', 'SGM.AU', 'SIG.AU', 'SIQ.AU', 'SLC.AU', 'SLX.AU', 
    'SMR.AU', 'SNL.AU', 'SNZ.AU', 'SOL.AU', 'SPK.AU', 'SRG.AU', 'SRL.AU', 'SSM.AU', 
    'STO.AU', 'SUL.AU', 'SUN.AU', 'SX2.AU', 'TAH.AU', 'TCL.AU', 'TEA.AU', 'TLS.AU', 
    'TLX.AU', 'TLC.AU', 'TNE.AU', 'TPG.AU', 'TPW.AU', 'TUA.AU', 'TWE.AU', 'VAU.AU', 
    'VCX.AU', 'VEA.AU', 'VGN.AU', 'VNT.AU', 'VUL.AU', 'WA1.AU', 'WAF.AU', 'WAM.AU', 
    'WBC.AU', 'WBT.AU', 'WDS.AU', 'WEB.AU', 'WES.AU', 'WGX.AU', 'WHC.AU', 'WLE.AU', 
    'WOR.AU', 'WOW.AU', 'WPR.AU', 'WTC.AU', 'XRO.AU', 'XYZ.AU', 'YAL.AU', 'ZIM.AU', 
    'ZIP.AU'
];