<?php
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Core 280: symbols_dynamic.php (268 .AU) + symbols_custom.php (12 extras).
 * Copied into the plugin so runtime does not depend on engine files.
 * Do not import unused symbols.php (ASX-300). XJO.INDX is fetched separately.
 */
function sig_core_symbols() {
    return array(
        'BHP.AU', 'CBA.AU', 'WBC.AU', 'NAB.AU',
        'ANZ.AU', 'MQG.AU', 'WES.AU', 'RIO.AU',
        'FMG.AU', 'GMG.AU', 'WDS.AU', 'TLS.AU',
        'TCL.AU', 'CSL.AU', 'WOW.AU', 'SIG.AU',
        'QBE.AU', 'ALL.AU', 'COL.AU', 'NST.AU',
        'STO.AU', 'EVN.AU', 'BXB.AU', 'S32.AU',
        'PLS.AU', 'CPU.AU', 'SCG.AU', 'REA.AU',
        'LYC.AU', 'ORG.AU', 'SUN.AU', 'FPH.AU',
        'IAG.AU', 'SGH.AU', 'SOL.AU', 'RMD.AU',
        'MIN.AU', 'QAN.AU', 'BSL.AU', 'PME.AU',
        'APA.AU', 'MPL.AU', 'IFT.AU', 'XRO.AU',
        'NEM.AU', 'WTC.AU', 'TLC.AU', 'ALQ.AU',
        'VCX.AU', 'AIA.AU', 'NXT.AU', 'JHX.AU',
        'ORI.AU', 'SGP.AU', 'TNE.AU', 'SHL.AU',
        'CHC.AU', 'LNW.AU', 'CAR.AU', 'GPT.AU',
        'GGP.AU', 'SFR.AU', 'ASX.AU', 'YAL.AU',
        'QUB.AU', 'RHC.AU', 'REH.AU', 'MCY.AU',
        'JBH.AU', 'AMC.AU', 'CDA.AU', 'LTR.AU',
        'TPG.AU', 'IGO.AU', 'WHC.AU', 'ALX.AU',
        'AZJ.AU', 'PRU.AU', 'HUB.AU', 'ARG.AU',
        'GMD.AU', 'MGR.AU', 'DNL.AU', 'COH.AU',
        'CMM.AU', 'WOR.AU', 'MEZ.AU', 'RMS.AU',
        'CGF.AU', 'DXS.AU', 'BEN.AU', 'APE.AU',
        'AGL.AU', 'HVN.AU', 'DOW.AU', 'NWL.AU',
        'SGM.AU', 'EDV.AU', 'CWY.AU', 'VNT.AU',
        'PDN.AU', 'NHC.AU', 'WGX.AU', 'RRL.AU',
        'NIC.AU', 'SDF.AU', 'SEK.AU', 'TLX.AU',
        'VAU.AU', 'CEN.AU', 'GQG.AU', 'BRG.AU',
        'BOQ.AU', 'AMP.AU', 'AAI.AU', 'ANN.AU',
        'EMR.AU', 'BFL.AU', 'A2M.AU', 'XYZ.AU',
        'PNI.AU', 'WAF.AU', 'PDI.AU', 'NWH.AU',
        'CNU.AU', 'VEA.AU', 'TWE.AU', 'AUB.AU',
        'ILU.AU', 'MTS.AU', 'EBO.AU', 'NHF.AU',
        'DRO.AU', 'MND.AU', 'SPK.AU', 'MFF.AU',
        'ZIP.AU', 'BWP.AU', 'LSF.AU', 'FBU.AU',
        'CSC.AU', 'MSB.AU', 'MP1.AU', 'GNE.AU',
        'RSG.AU', 'DBI.AU', 'L1G.AU', 'SUL.AU',
        'OBM.AU', 'RGN.AU', 'HDN.AU', 'LOV.AU',
        'CIA.AU', 'CLW.AU', 'ELV.AU', 'SMR.AU',
        'BPT.AU', 'SRL.AU', 'AUI.AU', 'DRR.AU',
        'RWC.AU', 'EOS.AU', 'BGL.AU', 'FLT.AU',
        'CQR.AU', 'MAH.AU', 'VGN.AU', 'IMD.AU',
        'NXG.AU', 'EVT.AU', 'ALK.AU', 'DVP.AU',
        'PMV.AU', 'GYG.AU', 'REG.AU', 'IPX.AU',
        'PRN.AU', 'CBO.AU', 'SRG.AU', 'GNP.AU',
        'MAQ.AU', 'MI6.AU', 'FRW.AU', 'VUL.AU',
        'RYM.AU', 'PXA.AU', 'LLC.AU', 'ASK.AU',
        'DDR.AU', 'CIP.AU', 'BRE.AU', 'TEA.AU',
        'MGH.AU', 'PPT.AU', 'NEU.AU', 'GLF.AU',
        'WLE.AU', 'SLC.AU', 'TAH.AU', 'WAM.AU',
        'ZIM.AU', 'JDO.AU', 'NWS.AU', 'WBT.AU',
        'SLX.AU', 'RDX.AU', 'DMP.AU', 'MAD.AU',
        'ASB.AU', 'BGA.AU', 'ELS.AU', 'CNI.AU',
        'GOZ.AU', 'GDG.AU', 'KCN.AU', 'ARB.AU',
        'ORA.AU', 'ABB.AU', 'MFG.AU', 'FFM.AU',
        'SIQ.AU', 'INA.AU', 'WPR.AU', 'DYL.AU',
        'SNZ.AU', 'NEC.AU', 'SSM.AU', 'DGT.AU',
        'BKI.AU', 'PGF.AU', 'NGI.AU', 'MLX.AU',
        'DTL.AU', 'LIN.AU', 'KAR.AU', 'CYL.AU',
        'SNL.AU', 'PYC.AU', 'HLI.AU', 'ARFA.AU',
        'MMS.AU', 'HMC.AU', 'MAF.AU', 'SX2.AU',
        'ARU.AU', 'NCK.AU', 'KLS.AU', 'ELD.AU',
        'AIZ.AU', 'PNR.AU', 'NUF.AU', 'CMW.AU',
        'TUAS.AU', 'IRE.AU', 'GNC.AU', 'SXE.AU',
        'APZ.AU', 'RIC.AU', 'SKS.AU', 'CKF.AU',
        'BVS.AU', 'A4N.AU', 'CHI.AU', 'CAT.AU',
        'BCI.AU', 'ERA.AU', 'OCL.AU', 'CCL.AU',
        'AAPL.US', 'TSLA.US', 'SPCX.US', 'GOOG.US',
        'MSFT.US', 'BTC-USD.CC', 'GHHF.AU', 'VAS.AU',
        'VHY.AU', 'STP.AU', 'GDX.AU', 'IOO.AU',
    );
}

